# Generated by Django 2.2.6 on 2019-10-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=45)),
                ('genero', models.CharField(max_length=25)),
                ('autor', models.CharField(max_length=50)),
            ],
        ),
    ]
